Fixed #3
Alex7Kom/nano-nanoid-cc pull request #6
Opened 2018-02-08 22:11 UTC by Kelin2025

Fixed #3  
P.S. Sorry for code format. It would be better to have some .eslintrc/.prettierrc in repository for these situations

2018-02-08 22:57 UTC, Kelin2025 commented on src/index.js
> +    }, ''),
Added uniqAlphabet field here

2018-02-08 22:57 UTC, Kelin2025 commented on src/index.js
> +    return
Replaced `alphabet` to `uniqAlphabet`

2018-02-08 22:57 UTC, Kelin2025 commented on src/index.js
> +  var randomBits = Math.log(input.uniqAlphabet.length) / Math.LN2
Replaced `alphabet` to `uniqAlphabet`

2018-02-08 22:57 UTC, Kelin2025 commented on src/index.js
> +  if (input.uniqAlphabet.length < 2 || input.size <= 1) {
Replaced `alphabet` to `uniqAlphabet`

2018-02-08 22:58 UTC, Kelin2025 commented on src/index.js
> +  if (input.uniqAlphabet.length < 2) {
Replaced `alphabet` to `uniqAlphabet`

2018-02-08 22:58 UTC, Kelin2025 commented on src/index.js
> +  if (input.uniqAlphabet.length > 256) {
Replaced `alphabet` to `uniqAlphabet`

2018-02-09 13:58 UTC, Alex7Kom commented
Thank you for PR!

I've added eslint/prettier to the project. Could you please rebase your changes on the current master?

2018-02-09 14:03 UTC, Alex7Kom commented
Actually I think it's better to error with a different message if alphabet contains duplicate symbols than simply remove them, so the user knows what happened.

2018-02-09 17:15 UTC, Kelin2025 commented
Added warning about duplicated symbols. I think we shouldn't remove duplicated symbols automatically because it may confuse people
![image](https://user-images.githubusercontent.com/4208480/36040175-d0f88246-0dd5-11e8-82fc-3cde36ab079c.png)

2018-02-10 08:03 UTC, alex7kom requested changes

2018-02-10 08:03 UTC, Alex7Kom commented on src/index.js
> +      return res.includes(letter) ? res : res + letter;
`String#includes` is ES6, so it doesn't work in IE.

2018-02-10 09:58 UTC, Kelin2025 commented on src/index.js
> +    }, ''),
Changed .includes() to .indexOf()

2018-02-10 09:59 UTC, Kelin2025 commented
@Alex7Kom it's ok now

2018-02-11 10:09 UTC, alex7kom approved these changes

2018-02-11 10:10 UTC, merged

2018-02-11 10:10 UTC, Alex7Kom commented
Thank you!